# Generated by Django 5.2.17 on 2026-09-02 19:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160, unique=True)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("code", models.SlugField()),
                ("timezone", models.CharField(default="Asia/Karachi", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="tenancy.company",
                    ),
                ),
            ],
            options={
                "ordering": ["company__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Dialer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("api_url", models.URLField(max_length=500)),
                ("api_username", models.CharField(max_length=120)),
                (
                    "api_password_ciphertext",
                    models.TextField(blank=True, editable=False),
                ),
                ("api_source", models.CharField(default="qa_portal", max_length=120)),
                (
                    "webhook_secret_hash",
                    models.CharField(blank=True, editable=False, max_length=256),
                ),
                (
                    "allowed_recording_hosts",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated hostnames permitted for recording downloads.",
                    ),
                ),
                (
                    "request_timeout_seconds",
                    models.PositiveSmallIntegerField(default=15),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dialers",
                        to="tenancy.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["branch__company__name", "branch__name", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(
                fields=("company", "code"), name="unique_branch_code_per_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="dialer",
            constraint=models.UniqueConstraint(
                fields=("branch", "name"), name="unique_dialer_name_per_branch"
            ),
        ),
    ]
