# Generated by Django 5.2.17 on 2026-09-08

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0002_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="DialerCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("campaign", models.CharField(max_length=120)),
                ("project_name", models.CharField(max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dialer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="tenancy.dialer",
                    ),
                ),
            ],
            options={
                "ordering": ["dialer__name", "campaign"],
            },
        ),
        migrations.AddConstraint(
            model_name="dialercampaign",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("campaign"),
                models.F("dialer"),
                name="unique_campaign_per_dialer_ci",
            ),
        ),
    ]
