# Generated by Django 5.2.17 on 2026-09-09 15:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def assign_existing_qas_to_branch_projects(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    DialerCampaign = apps.get_model("tenancy", "DialerCampaign")
    QAProjectAssignment = apps.get_model("tenancy", "QAProjectAssignment")
    campaigns_by_branch = {}
    for campaign_id, branch_id in DialerCampaign.objects.values_list(
        "id", "dialer__branch_id"
    ):
        campaigns_by_branch.setdefault(branch_id, []).append(campaign_id)

    assignments = []
    for qa_id, branch_id in User.objects.filter(
        role="qa", is_superuser=False, branch__isnull=False
    ).values_list("id", "branch_id"):
        assignments.extend(
            QAProjectAssignment(qa_id=qa_id, dialer_campaign_id=campaign_id)
            for campaign_id in campaigns_by_branch.get(branch_id, [])
        )
    QAProjectAssignment.objects.bulk_create(assignments, batch_size=500)


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0003_dialercampaign"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QAProjectAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dialer_campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_assignments",
                        to="tenancy.dialercampaign",
                    ),
                ),
                (
                    "qa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_project_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "qa__first_name",
                    "qa__last_name",
                    "dialer_campaign__dialer__name",
                    "dialer_campaign__project_name",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("qa", "dialer_campaign"),
                        name="unique_qa_project_assignment",
                    )
                ],
            },
        ),
        migrations.RunPython(
            assign_existing_qas_to_branch_projects, migrations.RunPython.noop
        ),
    ]
