# Generated by Django 5.2.17 on 2026-09-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authenticationevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("login_success", "Login success"),
                    ("login_failure", "Login failure"),
                    ("logout", "Logout"),
                    ("password_reset_request", "Password reset requested"),
                    ("password_reset", "Password reset"),
                    ("password_change", "Password changed"),
                ],
                max_length=40,
            ),
        ),
    ]
