# Generated by Django 5.2.17 on 2026-10-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_profile_and_appearance"),
    ]

    # Choices/default only: retain legacy preferences for safe upgrade/rollback.
    # The API normalizes legacy presets to Default without rewriting user rows.
    operations = [
        migrations.AlterField(
            model_name="user",
            name="appearance_preset",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("mui", "MUI"),
                    ("shadcn", "shadcn"),
                    ("glass", "Glass"),
                    ("geek", "Geek"),
                ],
                default="default",
                max_length=24,
            ),
        ),
    ]
