# Generated by Django 5.2.17 on 2026-09-02 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CallEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_key", models.CharField(max_length=64)),
                (
                    "event_type",
                    models.CharField(
                        choices=[("dispo", "Disposition"), ("no_agent", "No agent")],
                        max_length=20,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "call_id",
                    models.CharField(blank=True, db_index=True, max_length=160),
                ),
                (
                    "unique_id",
                    models.CharField(blank=True, db_index=True, max_length=160),
                ),
                ("lead_id", models.CharField(blank=True, db_index=True, max_length=80)),
                ("agent_log_id", models.CharField(blank=True, max_length=80)),
                (
                    "agent_user",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                (
                    "campaign",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("phone_number", models.CharField(blank=True, max_length=40)),
                ("list_id", models.CharField(blank=True, max_length=80)),
                (
                    "disposition",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                ("talk_time", models.PositiveIntegerField(default=0)),
                ("termination_reason", models.CharField(blank=True, max_length=160)),
                (
                    "call_date",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("source_recording_id", models.CharField(blank=True, max_length=160)),
                (
                    "source_recording_filename",
                    models.CharField(blank=True, max_length=255),
                ),
                ("recording_source_url", models.URLField(blank=True, max_length=1000)),
                (
                    "recording_uuid",
                    models.UUIDField(blank=True, null=True, unique=True),
                ),
                ("recording_path", models.CharField(blank=True, max_length=1000)),
                (
                    "recording_size_bytes",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("recording_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "recording_lookup_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("retrying", "Retrying"),
                            ("found", "Found"),
                            ("downloading", "Downloading"),
                            ("downloaded", "Downloaded"),
                            ("not_found", "Not found"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "recording_lookup_attempts",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("recording_lookup_last_error", models.TextField(blank=True)),
                (
                    "recording_download_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("retrying", "Retrying"),
                            ("found", "Found"),
                            ("downloading", "Downloading"),
                            ("downloaded", "Downloaded"),
                            ("not_found", "Not found"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "recording_download_attempts",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("recording_download_last_error", models.TextField(blank=True)),
                ("raw_payload", models.JSONField(default=dict)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="call_events",
                        to="tenancy.branch",
                    ),
                ),
                (
                    "dialer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="call_events",
                        to="tenancy.dialer",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("disputed", "Disputed"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "call",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review",
                        to="calls.callevent",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.AddIndex(
            model_name="callevent",
            index=models.Index(
                fields=["branch", "-received_at"], name="calls_calle_branch__8fd264_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callevent",
            index=models.Index(
                fields=["branch", "recording_download_status"],
                name="calls_calle_branch__d5fcbd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="callevent",
            index=models.Index(
                fields=["branch", "campaign", "-received_at"],
                name="calls_calle_branch__f5e496_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="callevent",
            constraint=models.UniqueConstraint(
                fields=("dialer", "event_key"), name="unique_event_per_dialer"
            ),
        ),
    ]
