# Generated by Django 5.2.17 on 2026-09-04

import re

import django.db.models.deletion
from django.db import migrations, models


TEAM_SEPARATOR = re.compile(r"\s*[-‐‑‒–—]\s*", re.UNICODE)


def backfill_agent_identity(apps, schema_editor):
    CallEvent = apps.get_model("calls", "CallEvent")
    for event in CallEvent.objects.only("id", "raw_payload").iterator(chunk_size=500):
        full_name = str((event.raw_payload or {}).get("agent_full_name") or "").strip()
        if not full_name:
            continue
        pieces = TEAM_SEPARATOR.split(full_name, maxsplit=1)
        if len(pieces) == 2 and pieces[0].strip() and pieces[1].strip():
            team_name, agent_name = pieces[0].strip(), pieces[1].strip()
        else:
            team_name, agent_name = "", full_name
        CallEvent.objects.filter(pk=event.pk).update(
            team_name=team_name[:160], agent_name=agent_name[:160]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("calls", "0001_initial"),
        ("tenancy", "0002_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="callevent",
            name="agent_name",
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
        migrations.AddField(
            model_name="callevent",
            name="team_name",
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
        migrations.AddField(
            model_name="callevent",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="call_events",
                to="tenancy.team",
            ),
        ),
        migrations.RunPython(backfill_agent_identity, migrations.RunPython.noop),
    ]
