# Generated by Django 5.2.17 on 2026-09-09

from django.db import migrations, models


def backfill_call_direction(apps, schema_editor):
    CallEvent = apps.get_model("calls", "CallEvent")
    pending = []
    for event in CallEvent.objects.only("id", "raw_payload").iterator(chunk_size=500):
        payload = event.raw_payload or {}
        close_call_id = str(payload.get("closecallid") or "").strip()
        event.close_call_id = close_call_id[:160]
        event.closer_group = str(payload.get("group") or "").strip()[:120]
        event.did_id = str(payload.get("did_id") or "").strip()[:80]
        event.did_pattern = str(payload.get("did_pattern") or "").strip()[:160]
        event.call_direction = (
            "INBOUND"
            if close_call_id and close_call_id.upper() not in {"0", "NULL"}
            else "OUTBOUND"
        )
        pending.append(event)
        if len(pending) == 500:
            CallEvent.objects.bulk_update(
                pending,
                [
                    "close_call_id",
                    "closer_group",
                    "did_id",
                    "did_pattern",
                    "call_direction",
                ],
            )
            pending.clear()
    if pending:
        CallEvent.objects.bulk_update(
            pending,
            [
                "close_call_id",
                "closer_group",
                "did_id",
                "did_pattern",
                "call_direction",
            ],
        )


class Migration(migrations.Migration):
    dependencies = [
        ("calls", "0003_assign_team_leader_prefixes"),
    ]

    operations = [
        migrations.AddField(
            model_name="callevent",
            name="call_direction",
            field=models.CharField(
                choices=[("INBOUND", "Inbound"), ("OUTBOUND", "Outbound")],
                db_index=True,
                default="OUTBOUND",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="callevent",
            name="close_call_id",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="callevent",
            name="closer_group",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="callevent",
            name="did_id",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="callevent",
            name="did_pattern",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.RunPython(backfill_call_direction, migrations.RunPython.noop),
    ]
