# Generated by Django 5.2.17 on 2026-09-08 19:39

from django.db import migrations, models


def backfill_extended_call_direction(apps, schema_editor):
    CallEvent = apps.get_model("calls", "CallEvent")
    empty_values = {"0", "NULL", "NONE"}
    pending = []

    def clean(value):
        return str(value or "").strip()

    for event in CallEvent.objects.all().iterator(chunk_size=500):
        payload = event.raw_payload or {}
        closecallid = clean(payload.get("closecallid"))
        xfercallid = clean(payload.get("xfercallid"))
        did_id = clean(payload.get("did_id"))
        did_pattern = clean(payload.get("did_pattern"))
        valid_closecall = bool(closecallid and closecallid.upper() not in empty_values)
        valid_xfercall = bool(xfercallid and xfercallid.upper() not in empty_values)
        has_did = bool(
            (did_id and did_id.upper() not in empty_values)
            or (did_pattern and did_pattern.upper() not in empty_values)
        )

        event.xfer_call_id = xfercallid[:160]
        if valid_closecall and has_did:
            event.call_direction = "INBOUND"
        elif valid_closecall and valid_xfercall:
            event.call_direction = "TRANSFER"
        elif valid_closecall:
            event.call_direction = "CLOSER"
        else:
            event.call_direction = "OUTBOUND"
        pending.append(event)

        if len(pending) == 500:
            CallEvent.objects.bulk_update(
                pending, ["xfer_call_id", "call_direction"], batch_size=500
            )
            pending.clear()

    if pending:
        CallEvent.objects.bulk_update(
            pending, ["xfer_call_id", "call_direction"], batch_size=500
        )


class Migration(migrations.Migration):
    dependencies = [
        ("calls", "0004_call_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="callevent",
            name="xfer_call_id",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name="callevent",
            name="call_direction",
            field=models.CharField(
                choices=[
                    ("INBOUND", "Inbound"),
                    ("TRANSFER", "Transfer"),
                    ("CLOSER", "Closer"),
                    ("OUTBOUND", "Outbound"),
                ],
                db_index=True,
                default="OUTBOUND",
                max_length=10,
            ),
        ),
        migrations.RunPython(
            backfill_extended_call_direction, migrations.RunPython.noop
        ),
    ]
